# Generated by Django 6.1.1 on 2026-09-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_1', '0003_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='text_uz',
            field=models.TextField(null=True),
        ),
    ]
