# Generated by Django 6.1.1 on 2026-09-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_1', '0004_category_name_en_category_name_ru_category_name_uz_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
